### ISSUE TITLE
Timing out

### ISSUE THREAD

**Issue by qkdreyer** [Yuyz0112/icomoon-cli#1]
FWIW, the first execution worked, but since then I'm getting this timeout error :

```
#set0 .miBox:not(.mi-selected) is not visible after 60000ms.
```

**Comment by Yuyz0112** [comment]
icomoon-cli checked this css selector to ensure the icon set was imported. AFAIK icomoon store some data in localStorage, like the icon set you have selected.
This assertion may failed when there is already a selected set from localStorage.

But headless chrome should launch without any localStorage data and this assertion never failed in my computer. 

Since headless mode is hard to debug, I may add a option to launch chrome in visible mode, would you mind wait until I add this feature and help me find out what happens in your situation? May be hours later when I was free.

**Comment by qkdreyer** [comment]
I've added the {visible: true} options to Chromy, and added a few debugging lines.
You may view the result here : http://recordit.co/OK0piEVHbs

**Comment by Yuyz0112** [comment]
Thanks a lot, I think I can reproduce it. Did you use a selection.json file with an empty icons array?

**Comment by qkdreyer** [comment]
Indeed.

```json
{
  "IcoMoonType": "selection",
  "icons": [],
  "height": 1024,
  "metadata": {
    "name": "icomoon"
  },
  "preferences": {
    "showGlyphs": true,
    "showQuickUse": true,
    "showQuickUse2": true,
    "showSVGs": true,
    "fontPref": {
      "prefix": "icon-",
      "metadata": {
        "fontFamily": "icomoon",
        "majorVersion": 1,
        "minorVersion": 0
      },
      "metrics": {
        "emSize": 1024,
        "baseline": 6.25,
        "whitespace": 50
      },
      "embed": false
    },
    "imagePref": {
      "prefix": "icon-",
      "png": true,
      "useClassSelector": true,
      "color": 0,
      "bgColor": 16777215,
      "classSelector": ".icon"
    },
    "historySize": 50,
    "showCodes": true,
    "gridSize": 16
  }
}
```

**Comment by Yuyz0112** [comment]
Okay, I think this is a bug because empty icons set will not have a menu button for the following operations.

![image](https://user-images.githubusercontent.com/13651389/36033389-e1214df4-0deb-11e8-9e05-fcb24efacc43.png)

Maybe you can manualy add one icon and download the selection.json file as your base icon set.
Or we can add a temp icon as the 'placeholder' if the icon set is empty, and remove it after import new icons, but it's tricky and hard to maintain.

**Comment by Yuyz0112** [comment]
I found there is a 'New Empty Set' operation in the left top menu. So it would be better to check selection.json file and if there is an empty icon set, icomoon-cli will add a new empty set by click the menu button.

@qkdreyer 
I would like to code this in the weekend, but if you like to make a PR (which is great), please comment in this issue and let me know.

**Comment by qkdreyer** [comment]
https://github.com/Yuyz0112/icomoon-cli/pull/2

**Comment by Yuyz0112** [comment]
@qkdreyer just add a improve commit 8e3e0dcd8ba7ef81c7c124107a57ad4032c57d99

**Comment by qkdreyer** [comment]
Thanks !

**Comment by pavermakov** [comment]
this is still happening
